package com.xworkz.lombok.content;

public enum Location {
 
	ASHOKNAGAR,SHANTHALANAGAR,BANNERGHATTAROAD,MAHADEVAPURA,RAJAJINAGAR,MALLESWARAM,VIKRAMNAGAR,
	KORAMANGALA,THANISANDRA,MAGRATHROAD,WHITEFIELD,CUNNINGHAMROAD,JPNAGAR;
}
