package com.xworkz.collection.runner;

import java.util.Collection;
import java.util.Iterator;
import java.util.LinkedList;

import com.xworkz.collection.dto.CountryDTO;
import com.xworkz.collection.dto.MatchBoxDto;
import com.xworkz.collection.run.Code;
import com.xworkz.collection.run.Continent;

public class CountryRunner {

	public static void main(String[] args) {
		CountryDTO<String, Integer, String> countryDTO1 = new CountryDTO<String, Integer, String>("AFGHANISTAN", Code.AFGHANISTAN, 12457863, "laxmi", Continent.ASIA);
		CountryDTO<String, Integer, String> countryDTO2 = new CountryDTO<String, Integer, String>("ALBANIA", Code.ALBANIA, 2877797, "Bledi", Continent.EUROPE);
		CountryDTO<String, Integer, String> countryDTO3 = new CountryDTO<String, Integer, String>("ALGERIA", Code.ALGERIA, 43851044, "Aymen", Continent.AFRICA);
		CountryDTO<String, Integer, String> countryDTO4 = new CountryDTO<String, Integer, String>("ANDORRA", Code.ANDORRA, 77265, "Xavier", Continent.EUROPE);
		CountryDTO<String, Integer, String> countryDTO5 = new CountryDTO<String, Integer, String>("ANGOLA", Code.ANGOLA, 32866272, "João", Continent.AFRICA);
		CountryDTO<String, Integer, String> countryDTO6 = new CountryDTO<String, Integer, String>("ANTIGUA AND BARBUDA", Code.ANTIGUA_AND_BARBUDA, 97928, "Gaston", Continent.AMERICA);
		CountryDTO<String, Integer, String> countryDTO7 = new CountryDTO<String, Integer, String>("ARGENTINA", Code.ARGENTINA, 45195777, "Alberto", Continent.AMERICA);
		CountryDTO<String, Integer, String> countryDTO8 = new CountryDTO<String, Integer, String>("ARMENIA", Code.ARMENIA, 2963243, "Vahagn", Continent.ASIA);
		CountryDTO<String, Integer, String> countryDTO9 = new CountryDTO<String, Integer, String>("AUSTRALIA", Code.AUSTRALIA, 25687041, "Anthony", Continent.OCEANIA);
		CountryDTO<String, Integer, String> countryDTO10 = new CountryDTO<String, Integer, String>("AUSTRIA", Code.AUSTRIA, 8917205, "Karl", Continent.EUROPE);
		CountryDTO<String, Integer, String> countryDTO11 = new CountryDTO<String, Integer, String>("AZERBAIJAN", Code.AZERBAIJAN, 10139177, "Ilham", Continent.ASIA);
		CountryDTO<String, Integer, String> countryDTO12 = new CountryDTO<String, Integer, String>("BAHAMAS", Code.BAHAMAS, 400516, "Perry", Continent.AMERICA);
		CountryDTO<String, Integer, String> countryDTO13 = new CountryDTO<String, Integer, String>("BAHRAIN", Code.BAHRAIN, 1701575, "Hamad", Continent.ASIA);
		CountryDTO<String, Integer, String> countryDTO14 = new CountryDTO<String, Integer, String>("BANGLADESH", Code.BANGLADESH, 166303498, "Sheikh", Continent.ASIA);
		CountryDTO<String, Integer, String> countryDTO15 = new CountryDTO<String, Integer, String>("BARBADOS", Code.BARBADOS, 287375, "Mia", Continent.AMERICA);
		CountryDTO<String, Integer, String> countryDTO16 = new CountryDTO<String, Integer, String>("BELARUS", Code.BELARUS, 9449323, "Alexander", Continent.EUROPE);
		CountryDTO<String, Integer, String> countryDTO17 = new CountryDTO<String, Integer, String>("BELGIUM", Code.BELGIUM, 11589623, "Alexander", Continent.EUROPE);
		CountryDTO<String, Integer, String> countryDTO18 = new CountryDTO<String, Integer, String>("BELIZE", Code.BELIZE, 423968, "John", Continent.AMERICA);
		CountryDTO<String, Integer, String> countryDTO19 = new CountryDTO<String, Integer, String>("BENIN", Code.BENIN, 12123200, "Patrice", Continent.AFRICA);
		CountryDTO<String, Integer, String> countryDTO20 = new CountryDTO<String, Integer, String>("BHUTAN", Code.BHUTAN, 771612, "Lotay", Continent.ASIA);
		CountryDTO<String, Integer, String> countryDTO21 = new CountryDTO<String, Integer, String>("BOLIVIA", Code.BOLIVIA, 11673021, "Luis", Continent.AMERICA);
		CountryDTO<String, Integer, String> countryDTO22 = new CountryDTO<String, Integer, String>("BOSNIA AND HERZEGOVINA", Code.BOSNIA_AND_HERZEGOVINA, 3280819, "Željko", Continent.EUROPE);
		CountryDTO<String, Integer, String> countryDTO23 = new CountryDTO<String, Integer, String>("BOTSWANA", Code.BOTSWANA, 2141206, "Mokgweetsi", Continent.AFRICA);
		CountryDTO<String, Integer, String> countryDTO24 = new CountryDTO<String, Integer, String>("BRAZIL", Code.BRAZIL, 213993437, "Luiz", Continent.AMERICA);
		CountryDTO<String, Integer, String> countryDTO25 = new CountryDTO<String, Integer, String>("BRUNEI", Code.BRUNEI, 453300, "Hassanal", Continent.ASIA);
		CountryDTO<String, Integer, String> countryDTO26 = new CountryDTO<String, Integer, String>("BULGARIA", Code.BULGARIA, 6951482, "Kiril", Continent.EUROPE);
		CountryDTO<String, Integer, String> countryDTO27 = new CountryDTO<String, Integer, String>("BURKINA FASO", Code.BURKINA_FASO, 22500000, "Thomas", Continent.AFRICA);
		CountryDTO<String, Integer, String> countryDTO28 = new CountryDTO<String, Integer, String>("BURUNDI", Code.BURUNDI, 11890784, "Évariste", Continent.AFRICA);
		CountryDTO<String, Integer, String> countryDTO29 = new CountryDTO<String, Integer, String>("CABO VERDE", Code.CABO_VERDE, 543767, "Jorge", Continent.AFRICA);
		CountryDTO<String, Integer, String> countryDTO30 = new CountryDTO<String, Integer, String>("CAMBODIA", Code.CAMBODIA, 16718965, "Hun", Continent.ASIA);
		CountryDTO<String, Integer, String> countryDTO31 = new CountryDTO<String, Integer, String>("CAMEROON", Code.CAMEROON, 27710000, "Paul", Continent.AFRICA);
		CountryDTO<String, Integer, String> countryDTO32 = new CountryDTO<String, Integer, String>("CANADA", Code.CANADA, 38005238, "Justin", Continent.AMERICA);
		CountryDTO<String, Integer, String> countryDTO33 = new CountryDTO<String, Integer, String>("CENTRAL AFRICAN REPUBLIC", Code.CENTRAL_AFRICAN_REPUBLIC, 5496068, "Félix", Continent.AFRICA);
		CountryDTO<String, Integer, String> countryDTO34 = new CountryDTO<String, Integer, String>("CHAD", Code.CHAD, 15946876, "Mahamat", Continent.AFRICA);
		CountryDTO<String, Integer, String> countryDTO35 = new CountryDTO<String, Integer, String>("CHILE", Code.CHILE, 19236144, "Gabriel", Continent.AMERICA);
		CountryDTO<String, Integer, String> countryDTO36 = new CountryDTO<String, Integer, String>("CHINA", Code.CHINA, 1444216107, "Xi", Continent.ASIA);
		CountryDTO<String, Integer, String> countryDTO37 = new CountryDTO<String, Integer, String>("COLOMBIA", Code.COLOMBIA, 50882891, "Gustavo", Continent.AMERICA);
		CountryDTO<String, Integer, String> countryDTO38 = new CountryDTO<String, Integer, String>("COMOROS", Code.COMOROS, 806153, "Azali", Continent.AFRICA);
		CountryDTO<String, Integer, String> countryDTO39 = new CountryDTO<String, Integer, String>("CONGO, REPUBLIC OF THE", Code.CONGO_REPUBLIC_OF_THE, 5500000, "Denis", Continent.AFRICA);
		CountryDTO<String, Integer, String> countryDTO40 = new CountryDTO<String, Integer, String>("CONGO, DEMOCRATIC REPUBLIC OF THE", Code.CONGO_DEMOCRATIC_REPUBLIC_OF_THE, 89561403, "Felix", Continent.AFRICA);
		CountryDTO<String, Integer, String> countryDTO41 = new CountryDTO<String, Integer, String>("COSTA RICA", Code.COSTA_RICA, 5112987, "Rodrigo", Continent.AMERICA);
		CountryDTO<String, Integer, String> countryDTO42 = new CountryDTO<String, Integer, String>("CROATIA", Code.CROATIA, 4105267, "Andrej", Continent.EUROPE);
		CountryDTO<String, Integer, String> countryDTO43 = new CountryDTO<String, Integer, String>("CUBA", Code.CUBA, 11313400, "Miguel", Continent.AMERICA);
		CountryDTO<String, Integer, String> countryDTO44 = new CountryDTO<String, Integer, String>("CYPRUS", Code.CYPRUS, 1207359, "Nikolas", Continent.EUROPE);
		CountryDTO<String, Integer, String> countryDTO45 = new CountryDTO<String, Integer, String>("CZECHIA", Code.CZECHIA, 10708981, "Petr", Continent.EUROPE);
		CountryDTO<String, Integer, String> countryDTO46 = new CountryDTO<String, Integer, String>("DENMARK", Code.DENMARK, 5818553, "Mette", Continent.EUROPE);
		CountryDTO<String, Integer, String> countryDTO47 = new CountryDTO<String, Integer, String>("DJIBOUTI", Code.DJIBOUTI, 883560, "Ismail", Continent.AFRICA);
		CountryDTO<String, Integer, String> countryDTO48 = new CountryDTO<String, Integer, String>("DOMINICA", Code.DOMINICA, 71991, "Roosevelt", Continent.AMERICA);
		CountryDTO<String, Integer, String> countryDTO49 = new CountryDTO<String, Integer, String>("DOMINICAN REPUBLIC", Code.DOMINICAN_REPUBLIC, 10847904, "Luis", Continent.AMERICA);
		CountryDTO<String, Integer, String> countryDTO50 = new CountryDTO<String, Integer, String>("ECUADOR", Code.ECUADOR, 17643060, "Guillermo", Continent.AMERICA);
		CountryDTO<String, Integer, String> countryDTO51 = new CountryDTO<String, Integer, String>("EGYPT", Code.EGYPT, 102334155, "Abdel", Continent.AFRICA);
		CountryDTO<String, Integer, String> countryDTO52 = new CountryDTO<String, Integer, String>("EL SALVADOR", Code.EL_SALVADOR, 6486201, "Nayib", Continent.AMERICA);
		CountryDTO<String, Integer, String> countryDTO53 = new CountryDTO<String, Integer, String>("EQUATORIAL GUINEA", Code.EQUATORIALGUINEA, 1402985, "Teodoro", Continent.AFRICA);
		CountryDTO<String, Integer, String> countryDTO54 = new CountryDTO<String, Integer, String>("ERITREA", Code.ERITREA, 3546000, "Isaias", Continent.AFRICA);
		CountryDTO<String, Integer, String> countryDTO55 = new CountryDTO<String, Integer, String>("ESTONIA", Code.ESTONIA, 1326535, "Kaja", Continent.EUROPE);
		CountryDTO<String, Integer, String> countryDTO56 = new CountryDTO<String, Integer, String>("ESWATINI", Code.ESWATINI, 1160164, "Mswati", Continent.AFRICA);
		CountryDTO<String, Integer, String> countryDTO57 = new CountryDTO<String, Integer, String>("ETHIOPIA", Code.ETHIOPIA, 118000000, "Abiy", Continent.AFRICA);
		CountryDTO<String, Integer, String> countryDTO58 = new CountryDTO<String, Integer, String>("FIJI", Code.FIJI, 896445, "Sitiveni", Continent.OCEANIA);
		CountryDTO<String, Integer, String> countryDTO59 = new CountryDTO<String, Integer, String>("FINLAND", Code.FINLAND, 5540720, "Sanna", Continent.EUROPE);
		CountryDTO<String, Integer, String> countryDTO60 = new CountryDTO<String, Integer, String>("FRANCE", Code.FRANCE, 65273511, "Emmanuel", Continent.EUROPE);
		CountryDTO<String, Integer, String> countryDTO61 = new CountryDTO<String, Integer, String>("GABON", Code.GABON, 2225734, "Ali", Continent.AFRICA);
		CountryDTO<String, Integer, String> countryDTO62 = new CountryDTO<String, Integer, String>("GAMBIA", Code.GAMBIA, 2416661, "Adama", Continent.AFRICA);
		CountryDTO<String, Integer, String> countryDTO63 = new CountryDTO<String, Integer, String>("GEORGIA", Code.GEORGIA, 3989167, "Salome", Continent.ASIA);
		CountryDTO<String, Integer, String> countryDTO64 = new CountryDTO<String, Integer, String>("GERMANY", Code.GERMANY, 83783942, "Olaf", Continent.EUROPE);
		CountryDTO<String, Integer, String> countryDTO65 = new CountryDTO<String, Integer, String>("GHANA", Code.GHANA, 31072940, "Nana", Continent.AFRICA);
		CountryDTO<String, Integer, String> countryDTO66 = new CountryDTO<String, Integer, String>("GREECE", Code.GREECE, 10423054, "Kyriakos", Continent.EUROPE);
		CountryDTO<String, Integer, String> countryDTO67 = new CountryDTO<String, Integer, String>("GRENADA", Code.GRENADA, 11229, "Dickon", Continent.AMERICA);
		CountryDTO<String, Integer, String> countryDTO68 = new CountryDTO<String, Integer, String>("GUATEMALA", Code.GUATEMALA, 17915568, "Alejandro", Continent.AMERICA);
		CountryDTO<String, Integer, String> countryDTO69 = new CountryDTO<String, Integer, String>("GUINEA", Code.GUINEA, 13024576, "Alpha", Continent.AFRICA);
		CountryDTO<String, Integer, String> countryDTO70 = new CountryDTO<String, Integer, String>("GUINEA-BISSAU", Code.GUINEABISSAU, 1968001, "Umaro", Continent.AFRICA);
		CountryDTO<String, Integer, String> countryDTO71 = new CountryDTO<String, Integer, String>("GUYANA", Code.GUYANA, 786559, "Irfaan", Continent.AMERICA);
		CountryDTO<String, Integer, String> countryDTO72 = new CountryDTO<String, Integer, String>("HAITI", Code.HAITI, 11402528, "Ariel", Continent.AMERICA);
		CountryDTO<String, Integer, String> countryDTO73 = new CountryDTO<String, Integer, String>("HONDURAS", Code.HONDURAS, 9904607, "Xiomara", Continent.AMERICA);
		CountryDTO<String, Integer, String> countryDTO74 = new CountryDTO<String, Integer, String>("HUNGARY", Code.HUNGARY, 9660351, "Viktor", Continent.EUROPE);
		CountryDTO<String, Integer, String> countryDTO75 = new CountryDTO<String, Integer, String>("ICELAND", Code.ICELAND, 366418, "Katrín", Continent.EUROPE);
		CountryDTO<String, Integer, String> countryDTO76 = new CountryDTO<String, Integer, String>("INDIA", Code.INDIA, 1393409038, "Narendra", Continent.ASIA);
		CountryDTO<String, Integer, String> countryDTO77 = new CountryDTO<String, Integer, String>("INDONESIA", Code.INDONESIA, 273523615, "Joko", Continent.ASIA);
		CountryDTO<String, Integer, String> countryDTO78 = new CountryDTO<String, Integer, String>("IRAN", Code.IRAN, 83992949, "Ebrahim", Continent.ASIA);
		CountryDTO<String, Integer, String> countryDTO79 = new CountryDTO<String, Integer, String>("IRAQ", Code.IRAQ, 40222493, "Mohammed", Continent.ASIA);
		CountryDTO<String, Integer, String> countryDTO80 = new CountryDTO<String, Integer, String>("IRELAND", Code.IRELAND, 4937786, "Leo", Continent.EUROPE);
		CountryDTO<String, Integer, String> countryDTO81 = new CountryDTO<String, Integer, String>("ISRAEL", Code.ISRAEL, 8655535, "Yair", Continent.ASIA);
		CountryDTO<String, Integer, String> countryDTO82 = new CountryDTO<String, Integer, String>("ITALY", Code.ITALY, 60244639, "Giorgia", Continent.EUROPE);
		CountryDTO<String, Integer, String> countryDTO83 = new CountryDTO<String, Integer, String>("JAMAICA", Code.JAMAICA, 2961165, "Andrew", Continent.AMERICA);
		CountryDTO<String, Integer, String> countryDTO84 = new CountryDTO<String, Integer, String>("JAPAN", Code.JAPAN, 126476461, "Fumio", Continent.ASIA);
		CountryDTO<String, Integer, String> countryDTO85 = new CountryDTO<String, Integer, String>("JORDAN", Code.JORDAN, 10203134, "Bashar", Continent.ASIA);
		CountryDTO<String, Integer, String> countryDTO86 = new CountryDTO<String, Integer, String>("KAZAKHSTAN", Code.KAZAKHSTAN, 18776707, "Kassym-Jomart", Continent.ASIA);
		CountryDTO<String, Integer, String> countryDTO87 = new CountryDTO<String, Integer, String>("KENYA", Code.KENYA, 53771296, "William", Continent.AFRICA);
		CountryDTO<String, Integer, String> countryDTO88 = new CountryDTO<String, Integer, String>("KIRIBATI", Code.KIRIBATI, 11910, "Taneti", Continent.OCEANIA);
		CountryDTO<String, Integer, String> countryDTO89 = new CountryDTO<String, Integer, String>("KOREA, NORTH", Code.KOREANORTH, 25678700, "Kim", Continent.ASIA);
		CountryDTO<String, Integer, String> countryDTO90 = new CountryDTO<String, Integer, String>("KOREA, SOUTH", Code.KOREASOUTH, 51269185, "Yoon", Continent.ASIA);
		CountryDTO<String, Integer, String> countryDTO91 = new CountryDTO<String, Integer, String>("KOSOVO", Code.KOSOVO, 1831000, "Albin", Continent.EUROPE);
		CountryDTO<String, Integer, String> countryDTO92 = new CountryDTO<String, Integer, String>("KUWAIT", Code.KUWAIT, 4270561, "Sabah", Continent.ASIA);
		CountryDTO<String, Integer, String> countryDTO93 = new CountryDTO<String, Integer, String>("KYRGYZSTAN", Code.KYRGYZSTAN, 6531200, "Sadyr", Continent.ASIA);
		CountryDTO<String, Integer, String> countryDTO94 = new CountryDTO<String, Integer, String>("LAOS", Code.LAOS, 7275560, "Thongloun", Continent.ASIA);
		CountryDTO<String, Integer, String> countryDTO95 = new CountryDTO<String, Integer, String>("LATVIA", Code.LATVIA, 1886198, "Edgars", Continent.EUROPE);
		CountryDTO<String, Integer, String> countryDTO96 = new CountryDTO<String, Integer, String>("LEBANON", Code.LEBANON, 6855700, "Nabih", Continent.ASIA);
		CountryDTO<String, Integer, String> countryDTO97 = new CountryDTO<String, Integer, String>("LESOTHO", Code.LESOTHO, 2142249, "Moeketsi", Continent.AFRICA);
		CountryDTO<String, Integer, String> countryDTO98 = new CountryDTO<String, Integer, String>("LIBERIA", Code.LIBERIA, 5057681, "George", Continent.AFRICA);
		CountryDTO<String, Integer, String> countryDTO99 = new CountryDTO<String, Integer, String>("LIBYA", Code.LIBYA, 6871292, "Abdul", Continent.AFRICA);
		CountryDTO<String, Integer, String> countryDTO100 = new CountryDTO<String, Integer, String>("LIECHTENSTEIN", Code.LIECHTENSTEIN, 38128, "Daniel", Continent.EUROPE);
		CountryDTO<String, Integer, String> countryDTO101 = new CountryDTO<String, Integer, String>("LITHUANIA", Code.LITHUANIA, 2722289, "Gitanas", Continent.EUROPE);
		CountryDTO<String, Integer, String> countryDTO102 = new CountryDTO<String, Integer, String>("LUXEMBOURG", Code.LUXEMBOURG, 634814, "Xavier", Continent.EUROPE);
		CountryDTO<String, Integer, String> countryDTO103 = new CountryDTO<String, Integer, String>("MADAGASCAR", Code.MADAGASCAR, 27691018, "Andry", Continent.AFRICA);
		CountryDTO<String, Integer, String> countryDTO104 = new CountryDTO<String, Integer, String>("MALAWI", Code.MALAWI, 19129952, "Lazarus", Continent.AFRICA);
		CountryDTO<String, Integer, String> countryDTO105 = new CountryDTO<String, Integer, String>("MALAYSIA", Code.MALAYSIA, 33188200, "Anwar", Continent.ASIA);
		CountryDTO<String, Integer, String> countryDTO106 = new CountryDTO<String, Integer, String>("MALDIVES", Code.MALDIVES, 540544, "Mohamed", Continent.ASIA);
		CountryDTO<String, Integer, String> countryDTO107 = new CountryDTO<String, Integer, String>("MALI", Code.MALI, 20250833, "Assimi", Continent.AFRICA);
		CountryDTO<String, Integer, String> countryDTO108 = new CountryDTO<String, Integer, String>("MALTA", Code.MALTA, 514999, "Robert", Continent.EUROPE);
		CountryDTO<String, Integer, String> countryDTO109 = new CountryDTO<String, Integer, String>("MAROC", Code.MAROC, 36910560, "Aziz", Continent.AFRICA);
		CountryDTO<String, Integer, String> countryDTO110 = new CountryDTO<String, Integer, String>("MARSHALL ISLANDS", Code.MARSHALLISLANDS, 59094, "David", Continent.OCEANIA);
		CountryDTO<String, Integer, String> countryDTO111 = new CountryDTO<String, Integer, String>("MAURITANIA", Code.MAURITANIA, 4699000, "Mohamed", Continent.AFRICA);
		CountryDTO<String, Integer, String> countryDTO112 = new CountryDTO<String, Integer, String>("MAURITIUS", Code.MAURITIUS, 1271768, "Pravind", Continent.AFRICA);
		CountryDTO<String, Integer, String> countryDTO113 = new CountryDTO<String, Integer, String>("MEXICO", Code.MEXICO, 130262216, "Andrés", Continent.AMERICA);
		CountryDTO<String, Integer, String> countryDTO114 = new CountryDTO<String, Integer, String>("MICRONESIA", Code.MICRONESIA, 11500, "David", Continent.OCEANIA);
		CountryDTO<String, Integer, String> countryDTO115 = new CountryDTO<String, Integer, String>("MOLDOVA", Code.MOLDOVA, 2657637, "Dorin", Continent.EUROPE);
		CountryDTO<String, Integer, String> countryDTO116 = new CountryDTO<String, Integer, String>("MONACO", Code.MONACO, 39242, "Albert", Continent.EUROPE);
		CountryDTO<String, Integer, String> countryDTO117 = new CountryDTO<String, Integer, String>("MONGOLIA", Code.MONGOLIA, 3284910, "Ukhnaagiin", Continent.ASIA);
		CountryDTO<String, Integer, String> countryDTO118 = new CountryDTO<String, Integer, String>("MONTENEGRO", Code.MONTENEGRO, 622359, "Dritan", Continent.EUROPE);
		CountryDTO<String, Integer, String> countryDTO119 = new CountryDTO<String, Integer, String>("MOROCCO", Code.MOROCCO, 36910560, "Aziz", Continent.AFRICA);
		CountryDTO<String, Integer, String> countryDTO120 = new CountryDTO<String, Integer, String>("MOZAMBIQUE", Code.MOZAMBIQUE, 31804438, "Filipe", Continent.AFRICA);
		CountryDTO<String, Integer, String> countryDTO121 = new CountryDTO<String, Integer, String>("MYANMAR", Code.MYANMAR, 54795214, "Min", Continent.ASIA);
		CountryDTO<String, Integer, String> countryDTO122 = new CountryDTO<String, Integer, String>("NAMIBIA", Code.NAMIBIA, 2540905, "Hage", Continent.AFRICA);
		CountryDTO<String, Integer, String> countryDTO123 = new CountryDTO<String, Integer, String>("NAURU", Code.NAURU, 10834, "Lionel", Continent.OCEANIA);
		CountryDTO<String, Integer, String> countryDTO124 = new CountryDTO<String, Integer, String>("NEPAL", Code.NEPAL, 29609623, "Pushpa", Continent.ASIA);
		CountryDTO<String, Integer, String> countryDTO125 = new CountryDTO<String, Integer, String>("NETHERLANDS", Code.NETHERLANDS, 17134872, "Mark", Continent.EUROPE);
		CountryDTO<String, Integer, String> countryDTO126 = new CountryDTO<String, Integer, String>("NEW ZEALAND", Code.NEWZEALAND, 5083000, "Chris", Continent.OCEANIA);
		CountryDTO<String, Integer, String> countryDTO127 = new CountryDTO<String, Integer, String>("NICARAGUA", Code.NICARAGUA, 6624554, "Daniel", Continent.AMERICA);
		CountryDTO<String, Integer, String> countryDTO128 = new CountryDTO<String, Integer, String>("NIGER", Code.NIGER, 24420000, "Mohamed", Continent.AFRICA);
		CountryDTO<String, Integer, String> countryDTO129 = new CountryDTO<String, Integer, String>("NIGERIA", Code.NIGERIA, 211400708, "Bola", Continent.AFRICA);
		CountryDTO<String, Integer, String> countryDTO130 = new CountryDTO<String, Integer, String>("NORTH MACEDONIA", Code.NORTHMACEDONIA, 2083459, "Dimitar", Continent.EUROPE);
		CountryDTO<String, Integer, String> countryDTO131 = new CountryDTO<String, Integer, String>("NORWAY", Code.NORWAY, 5421241, "Jonas", Continent.EUROPE);
		CountryDTO<String, Integer, String> countryDTO132 = new CountryDTO<String, Integer, String>("OMAN", Code.OMAN, 5106626, "Haitham", Continent.ASIA);
		CountryDTO<String, Integer, String> countryDTO133 = new CountryDTO<String, Integer, String>("PAKISTAN", Code.PAKISTAN, 225199937, "Arif", Continent.ASIA);
		CountryDTO<String, Integer, String> countryDTO134 = new CountryDTO<String, Integer, String>("PALAU", Code.PALAU, 18000, "Surangel", Continent.OCEANIA);
		CountryDTO<String, Integer, String> countryDTO135 = new CountryDTO<String, Integer, String>("PANAMA", Code.PANAMA, 4314768, "Cortizo", Continent.AMERICA);
		CountryDTO<String, Integer, String> countryDTO136 = new CountryDTO<String, Integer, String>("PAPUA NEW GUINEA", Code.PAPUANEW_GUINEA, 8947027, "James", Continent.OCEANIA);
		CountryDTO<String, Integer, String> countryDTO137 = new CountryDTO<String, Integer, String>("PARAGUAY", Code.PARAGUAY, 7132538, "Santiago", Continent.AMERICA);
		CountryDTO<String, Integer, String> countryDTO138 = new CountryDTO<String, Integer, String>("PERU", Code.PERU, 32971854, "Dina", Continent.AMERICA);
		CountryDTO<String, Integer, String> countryDTO139 = new CountryDTO<String, Integer, String>("PHILIPPINES", Code.PHILIPPINES, 113881000, "Ferdinand", Continent.ASIA);
		CountryDTO<String, Integer, String> countryDTO140 = new CountryDTO<String, Integer, String>("POLAND", Code.POLAND, 38386000, "Mateusz", Continent.EUROPE);
		CountryDTO<String, Integer, String> countryDTO141 = new CountryDTO<String, Integer, String>("PORTUGAL", Code.PORTUGAL, 10196709, "António", Continent.EUROPE);
		CountryDTO<String, Integer, String> countryDTO142 = new CountryDTO<String, Integer, String>("QATAR", Code.QATAR, 2544200, "Tamim", Continent.ASIA);
		CountryDTO<String, Integer, String> countryDTO143 = new CountryDTO<String, Integer, String>("ROMANIA", Code.ROMANIA, 19237691, "Marcel", Continent.EUROPE);
		CountryDTO<String, Integer, String> countryDTO144 = new CountryDTO<String, Integer, String>("RUSSIA", Code.RUSSIA, 145912025, "Vladimir", Continent.ASIA);
		CountryDTO<String, Integer, String> countryDTO145 = new CountryDTO<String, Integer, String>("RWANDA", Code.RWANDA, 12952218, "Paul", Continent.AFRICA);
		CountryDTO<String, Integer, String> countryDTO146 = new CountryDTO<String, Integer, String>("SAINT KITTS AND NEVIS", Code.SAINT_KITTS_AND_NEVIS, 53192, "Terrance", Continent.AMERICA);
		CountryDTO<String, Integer, String> countryDTO147 = new CountryDTO<String, Integer, String>("SAINT LUCIA", Code.SAINTLUCIA, 183629, "Philip", Continent.AMERICA);
		CountryDTO<String, Integer, String> countryDTO148 = new CountryDTO<String, Integer, String>("SAINT VINCENT AND THE GRENADINES", Code.SAINT_VINCENT_AND_THE_GRENADINES, 110943, "Ralph", Continent.AMERICA);
		CountryDTO<String, Integer, String> countryDTO149 = new CountryDTO<String, Integer, String>("SAMOA", Code.SAMOA, 198410, "Fiamē", Continent.OCEANIA);
		CountryDTO<String, Integer, String> countryDTO150 = new CountryDTO<String, Integer, String>("SAN MARINO", Code.SANMARINO, 33931, "Francesco", Continent.EUROPE);
		CountryDTO<String, Integer, String> countryDTO151 = new CountryDTO<String, Integer, String>("SAUDI ARABIA", Code.SAUDIARABIA, 34813871, "Mohammed", Continent.ASIA);
		CountryDTO<String, Integer, String> countryDTO152 = new CountryDTO<String, Integer, String>("SENEGAL", Code.SENEGAL, 16425864, "Macky", Continent.AFRICA);
		CountryDTO<String, Integer, String> countryDTO153 = new CountryDTO<String, Integer, String>("SERBIA", Code.SERBIA, 8775055, "Aleksandar", Continent.EUROPE);
		CountryDTO<String, Integer, String> countryDTO154 = new CountryDTO<String, Integer, String>("SINGAPORE", Code.SINGAPORE, 5850342, "Lee", Continent.ASIA);
		CountryDTO<String, Integer, String> countryDTO155 = new CountryDTO<String, Integer, String>("SLOVAKIA", Code.SLOVAKIA, 5456362, "Eduard", Continent.EUROPE);
		CountryDTO<String, Integer, String> countryDTO156 = new CountryDTO<String, Integer, String>("SLOVENIA", Code.SLOVENIA, 2078654, "Robert", Continent.EUROPE);
		CountryDTO<String, Integer, String> countryDTO157 = new CountryDTO<String, Integer, String>("SOMALIA", Code.SOMALIA, 15893222, "Hassan", Continent.AFRICA);
		CountryDTO<String, Integer, String> countryDTO158 = new CountryDTO<String, Integer, String>("SOUTH AFRICA", Code.SOUTHAFRICA, 59308690, "Cyril", Continent.AFRICA);
		CountryDTO<String, Integer, String> countryDTO159 = new CountryDTO<String, Integer, String>("SOUTH SUDAN", Code.SOUTHSUDAN, 10910716, "Salva", Continent.AFRICA);
		CountryDTO<String, Integer, String> countryDTO160 = new CountryDTO<String, Integer, String>("SPAIN", Code.SPAIN, 46754778, "Pedro", Continent.EUROPE);
		CountryDTO<String, Integer, String> countryDTO161 = new CountryDTO<String, Integer, String>("SRI LANKA", Code.SRILANKA, 21919000, "Ranil", Continent.ASIA);
		CountryDTO<String, Integer, String> countryDTO162 = new CountryDTO<String, Integer, String>("SUDAN", Code.SUDAN, 43849260, "Abdalla", Continent.AFRICA);
		CountryDTO<String, Integer, String> countryDTO163 = new CountryDTO<String, Integer, String>("SURINAME", Code.SURINAME, 586634, "Chandrikapersad", Continent.AMERICA);
		CountryDTO<String, Integer, String> countryDTO164 = new CountryDTO<String, Integer, String>("SWEDEN", Code.SWEDEN, 10099265, "Ulf", Continent.EUROPE);
		CountryDTO<String, Integer, String> countryDTO165 = new CountryDTO<String, Integer, String>("SWITZERLAND", Code.SWITZERLAND, 8654622, "Alain", Continent.EUROPE);
		CountryDTO<String, Integer, String> countryDTO166 = new CountryDTO<String, Integer, String>("TAIWAN", Code.TAIWAN, 23816775, "Tsaai", Continent.ASIA);
		CountryDTO<String, Integer, String> countryDTO167 = new CountryDTO<String, Integer, String>("TAJIKISTAN", Code.TAJIKISTAN, 9537645, "Emomali", Continent.ASIA);
		CountryDTO<String, Integer, String> countryDTO168 = new CountryDTO<String, Integer, String>("TANZANIA", Code.TANZANIA, 59734218, "Samia", Continent.AFRICA);
		CountryDTO<String, Integer, String> countryDTO169 = new CountryDTO<String, Integer, String>("THAILAND", Code.THAILAND, 69424640, "Prayuth", Continent.ASIA);
		CountryDTO<String, Integer, String> countryDTO170 = new CountryDTO<String, Integer, String>("TUNISIA", Code.TUNISIA, 11818619, "Kais", Continent.AFRICA);
		CountryDTO<String, Integer, String> countryDTO171 = new CountryDTO<String, Integer, String>("TURKMENISTAN", Code.TURKMENISTAN, 6031200, "Berdimuhamedow", Continent.ASIA);
		CountryDTO<String, Integer, String> countryDTO172 = new CountryDTO<String, Integer, String>("TUVALU", Code.TUVALU, 11700, "Kausea", Continent.OCEANIA);
		CountryDTO<String, Integer, String> countryDTO173 = new CountryDTO<String, Integer, String>("UGANDA", Code.UGANDA, 45741007, "Yoweri", Continent.AFRICA);
		CountryDTO<String, Integer, String> countryDTO174 = new CountryDTO<String, Integer, String>("UKRAINE", Code.UKRAINE, 43733762, "Volodymyr", Continent.EUROPE);
		CountryDTO<String, Integer, String> countryDTO175 = new CountryDTO<String, Integer, String>("UNITED ARAB EMIRATES", Code.UNITED_ARAB_EMIRATES, 9775211, "Mohammed", Continent.ASIA);
		CountryDTO<String, Integer, String> countryDTO176 = new CountryDTO<String, Integer, String>("UNITED KINGDOM", Code.UNITEDKINGDOM, 68207114, "Rishi", Continent.EUROPE);
		CountryDTO<String, Integer, String> countryDTO177 = new CountryDTO<String, Integer, String>("UNITED STATES", Code.UNITEDSTATES, 331893745, "Joe", Continent.AMERICA);
		CountryDTO<String, Integer, String> countryDTO178 = new CountryDTO<String, Integer, String>("URUGUAY", Code.URUGUAY, 3487028, "Luis", Continent.AMERICA);
		CountryDTO<String, Integer, String> countryDTO179 = new CountryDTO<String, Integer, String>("UZBEKISTAN", Code.UZBEKISTAN, 34836679, "Shavkat", Continent.ASIA);
		CountryDTO<String, Integer, String> countryDTO180 = new CountryDTO<String, Integer, String>("VANUATU", Code.VANUATU, 307145, "Iona", Continent.OCEANIA);
		CountryDTO<String, Integer, String> countryDTO181 = new CountryDTO<String, Integer, String>("VATICAN CITY", Code.VATICANCITY, 801, "Francesco", Continent.EUROPE);
		CountryDTO<String, Integer, String> countryDTO182 = new CountryDTO<String, Integer, String>("VENEZUELA", Code.VENEZUELA, 28435943, "Nicolás", Continent.AMERICA);
		CountryDTO<String, Integer, String> countryDTO183 = new CountryDTO<String, Integer, String>("VIETNAM", Code.VIETNAM, 98168829, "Pham", Continent.ASIA);
		CountryDTO<String, Integer, String> countryDTO184 = new CountryDTO<String, Integer, String>("YEMEN", Code.YEMEN, 30025000, "Mansour", Continent.ASIA);
		CountryDTO<String, Integer, String> countryDTO185 = new CountryDTO<String, Integer, String>("ZAMBIA", Code.ZAMBIA, 18930296, "Hakainde", Continent.AFRICA);
		CountryDTO<String, Integer, String> countryDTO186 = new CountryDTO<String, Integer, String>("ZIMBABWE", Code.ZIMBABWE, 16752953, "Emmerson", Continent.AFRICA);
		CountryDTO<String, Integer, String> countryDTO187 = new CountryDTO<String, Integer, String>("VATICAN CITY", Code.VATICANCITY, 800, "Pope Francis", Continent.EUROPE);
		CountryDTO<String, Integer, String> countryDTO188 = new CountryDTO<String, Integer, String>("SOMALIA", Code.SOMALIA, 15893222, "Hassan Sheikh Mohamud", Continent.AFRICA);
		CountryDTO<String, Integer, String> countryDTO189 = new CountryDTO<String, Integer, String>("NEW ZEALAND", Code.NEWZEALAND, 5084300, "Chris Hipkins", Continent.OCEANIA);
		CountryDTO<String, Integer, String> countryDTO190 = new CountryDTO<String, Integer, String>("PANAMA", Code.PANAMA, 4314768, "Laurentino Cortizo", Continent.AMERICA);
		CountryDTO<String, Integer, String> countryDTO191 = new CountryDTO<String, Integer, String>("MALAWI", Code.MALAWI, 20210162, "Lazarus Chakwera", Continent.AFRICA);
		CountryDTO<String, Integer, String> countryDTO192 = new CountryDTO<String, Integer, String>("HONDURAS", Code.HONDURAS, 10139177, "Xiomara Castro", Continent.AMERICA);
		CountryDTO<String, Integer, String> countryDTO193 = new CountryDTO<String, Integer, String>("MALTA", Code.MALTA, 514999, "Robert Abela", Continent.EUROPE);
		CountryDTO<String, Integer, String> countryDTO194 = new CountryDTO<String, Integer, String>("BAHAMAS", Code.BAHAMAS, 400516, "Philip Davis", Continent.AMERICA);
		CountryDTO<String, Integer, String> countryDTO195 = new CountryDTO<String, Integer, String>("LAOS", Code.LAOS, 7494843, "Thongloun Sisoulith", Continent.ASIA);

		
		Collection <CountryDTO> collection=new LinkedList<CountryDTO>();
		collection.add(countryDTO1);
		collection.add(countryDTO2);
		collection.add(countryDTO3);
		collection.add(countryDTO4);
		collection.add(countryDTO5);
		collection.add(countryDTO6);
		collection.add(countryDTO7);
		collection.add(countryDTO8);
		collection.add(countryDTO9);
		collection.add(countryDTO10);
		collection.add(countryDTO11);
		collection.add(countryDTO12);
		collection.add(countryDTO13);
		collection.add(countryDTO14);
		collection.add(countryDTO15);
		collection.add(countryDTO16);
		collection.add(countryDTO17);
		collection.add(countryDTO18);
		collection.add(countryDTO19);
		collection.add(countryDTO20);
		collection.add(countryDTO21);
		collection.add(countryDTO22);
		collection.add(countryDTO23);
		collection.add(countryDTO24);
		collection.add(countryDTO25);
		collection.add(countryDTO26);
		collection.add(countryDTO27);
		collection.add(countryDTO28);
		collection.add(countryDTO29);
		collection.add(countryDTO30);
		collection.add(countryDTO31);
		collection.add(countryDTO32);
		collection.add(countryDTO33);
		collection.add(countryDTO34);
		collection.add(countryDTO35);
		collection.add(countryDTO36);
		collection.add(countryDTO37);
		collection.add(countryDTO38);
		collection.add(countryDTO39);
		collection.add(countryDTO40);
		collection.add(countryDTO41);
		collection.add(countryDTO42);
		collection.add(countryDTO43);
		collection.add(countryDTO44);
		collection.add(countryDTO45);
		collection.add(countryDTO46);
		collection.add(countryDTO47);
		collection.add(countryDTO48);
		collection.add(countryDTO49);
		collection.add(countryDTO50);
		collection.add(countryDTO51);
		collection.add(countryDTO52);
		collection.add(countryDTO53);
		collection.add(countryDTO54);
		collection.add(countryDTO55);
		collection.add(countryDTO56);
		collection.add(countryDTO57);
		collection.add(countryDTO58);
		collection.add(countryDTO59);
		collection.add(countryDTO60);
		collection.add(countryDTO61);
		collection.add(countryDTO62);
		collection.add(countryDTO63);
		collection.add(countryDTO64);
		collection.add(countryDTO65);
		collection.add(countryDTO66);
		collection.add(countryDTO67);
		collection.add(countryDTO68);
		collection.add(countryDTO69);
		collection.add(countryDTO70);
		collection.add(countryDTO71);
		collection.add(countryDTO72);
		collection.add(countryDTO73);
		collection.add(countryDTO74);
		collection.add(countryDTO75);
		collection.add(countryDTO76);
		collection.add(countryDTO77);
		collection.add(countryDTO78);
		collection.add(countryDTO79);
		collection.add(countryDTO80);
		collection.add(countryDTO81);
		collection.add(countryDTO82);
		collection.add(countryDTO83);
		collection.add(countryDTO84);
		collection.add(countryDTO85);
		collection.add(countryDTO86);
		collection.add(countryDTO87);
		collection.add(countryDTO88);
		collection.add(countryDTO89);
		collection.add(countryDTO90);
		collection.add(countryDTO91);
		collection.add(countryDTO92);
		collection.add(countryDTO93);
		collection.add(countryDTO94);
		collection.add(countryDTO95);
		collection.add(countryDTO96);
		collection.add(countryDTO97);
		collection.add(countryDTO98);
		collection.add(countryDTO99);
		collection.add(countryDTO100);
		collection.add(countryDTO101);
		collection.add(countryDTO102);
		collection.add(countryDTO103);
		collection.add(countryDTO104);
		collection.add(countryDTO105);
		collection.add(countryDTO106);
		collection.add(countryDTO107);
		collection.add(countryDTO108);
		collection.add(countryDTO109);
		collection.add(countryDTO110);
		collection.add(countryDTO111);
		collection.add(countryDTO112);
		collection.add(countryDTO113);
		collection.add(countryDTO114);
		collection.add(countryDTO115);
		collection.add(countryDTO116);
		collection.add(countryDTO117);
		collection.add(countryDTO118);
		collection.add(countryDTO119);
		collection.add(countryDTO120);
		collection.add(countryDTO121);
		collection.add(countryDTO122);
		collection.add(countryDTO123);
		collection.add(countryDTO124);
		collection.add(countryDTO125);
		collection.add(countryDTO126);
		collection.add(countryDTO127);
		collection.add(countryDTO128);
		collection.add(countryDTO129);
		collection.add(countryDTO130);
		collection.add(countryDTO131);
		collection.add(countryDTO132);
		collection.add(countryDTO133);
		collection.add(countryDTO134);
		collection.add(countryDTO135);
		collection.add(countryDTO136);
		collection.add(countryDTO137);
		collection.add(countryDTO138);
		collection.add(countryDTO139);
		collection.add(countryDTO140);
		collection.add(countryDTO141);
		collection.add(countryDTO142);
		collection.add(countryDTO143);
		collection.add(countryDTO144);
		collection.add(countryDTO145);
		collection.add(countryDTO146);
		collection.add(countryDTO147);
		collection.add(countryDTO148);
		collection.add(countryDTO149);
		collection.add(countryDTO150);
		collection.add(countryDTO151);
		collection.add(countryDTO152);
		collection.add(countryDTO153);
		collection.add(countryDTO154);
		collection.add(countryDTO155);
		collection.add(countryDTO156);
		collection.add(countryDTO157);
		collection.add(countryDTO158);
		collection.add(countryDTO159);
		collection.add(countryDTO160);
		collection.add(countryDTO161);
		collection.add(countryDTO162);
		collection.add(countryDTO163);
		collection.add(countryDTO164);
		collection.add(countryDTO165);
		collection.add(countryDTO166);
		collection.add(countryDTO167);
		collection.add(countryDTO168);
		collection.add(countryDTO169);
		collection.add(countryDTO170);
		collection.add(countryDTO171);
		collection.add(countryDTO172);
		collection.add(countryDTO173);
		collection.add(countryDTO174);
		collection.add(countryDTO175);
		collection.add(countryDTO176);
		collection.add(countryDTO177);
		collection.add(countryDTO178);
		collection.add(countryDTO179);
		collection.add(countryDTO180);
		collection.add(countryDTO181);
		collection.add(countryDTO182);
		collection.add(countryDTO183);
		collection.add(countryDTO184);
		collection.add(countryDTO185);
		collection.add(countryDTO186);
		collection.add(countryDTO187);
		collection.add(countryDTO188);
		collection.add(countryDTO189);
		collection.add(countryDTO190);
		collection.add(countryDTO191);
		collection.add(countryDTO192);
		collection.add(countryDTO193);
		collection.add(countryDTO194);
		collection.add(countryDTO195);
		
          Iterator<CountryDTO> iterator =collection.iterator();
		
		while(iterator.hasNext()) {
			CountryDTO ref=iterator.next();
			System.out.println(ref);
			
			if(ref.getPopulation()<250000) {
				System.out.println(ref.getName());
			}
			
	}

	}
	}

