class HelicopterRunner{
	public static void main(String[] args){
		System.out.println("start main method in Helicopter");
		new Helicopter();
		new Helicopter();
		new Helicopter();
		new Helicopter();
		new Helicopter();
		Helicopter helicopter=new Helicopter();
		System.out.println("++++++++++++++");
		new Market();
		new Market();
		new Market();
		new Market();
		new Market();
		Market market = new Market();
		System.out.println("++++++++++++");
		new Mall();
		new Mall();
		new Mall();
		new Mall();
		new Mall();
		Mall mall=new Mall();
	    System.out.println("++++++++++++");
		new Train1();
		new Train1();
		new Train1();
		new Train1();
		new Train1();
		 Train1 train=new Train1();
		 System.out.println("++++++++++++");
		 new Ring();
		 new Ring();
		 new Ring();
		 new Ring();
		 new Ring();
		 Ring ring = new Ring();
		 System.out.println("++++++++++++");
		new Auto();
		new Auto();
		new Auto();
		new Auto();
		new Auto();
		 Auto auto=new Auto();
		 System.out.println("++++++++++++");
		 new Auditorium();
		 new Auditorium();
		 new Auditorium();
		 new Auditorium();
		 new Auditorium();
		Auditorium auditorium= new Auditorium();
		 System.out.println("++++++++++++");
		 new SpaceShip();
		 new SpaceShip();
		 new SpaceShip();
		 new SpaceShip();
		 new SpaceShip();
		SpaceShip spaceShip= new SpaceShip();
		System.out.println("end main method in Helicopter");
	}
}