class RupeeRunner{
	public static void main(String[] args){
		System.out.println("start main in RupeeRunner ");
		Rupee rupee =new Rupee();
		 String color= rupee.color;
		 String shape=rupee.shape;
		 double thingNess=rupee.thingNess;
		System.out.println("rupee color:"+color);
			System.out.println("rupee shape:"+shape);
				System.out.println("rupee thingness:"+thingNess);
				System.out.println("+++++++++++++");
				AirCondition rupee1 =new AirCondition();
				String brand=rupee1.brand;
	            String color1=rupee1.color;
	            float price=rupee1.price;
				System.out.println("AirCondition brand:"+brand);
				System.out.println("AirCondition color:"+color1);
				System.out.println("AirCondition price:"+price);
				System.out.println("+++++++++++++");
				AutoRikshaw Auto=new AutoRikshaw();
				String numberPlate=Auto.numberPlate;
	int licenseNumber=Auto.licenseNumber;
	String driverName=Auto.driverName;
	System.out.println("AutoRikshaw numberPlate:"+numberPlate);
	System.out.println("AutoRikshaw licenseNumber:"+licenseNumber);
	System.out.println("AutoRikshaw driverName:"+driverName);
	System.out.println("+++++++++++++");
	AutoDriver driver=new AutoDriver();
	int age=driver.age;
	String name =driver.name;
	long phoneNo =driver.phoneNo;
	System.out.println("AutoDriver Age:"+age);
	System.out.println("AutoDriver Name:"+name);
	System.out.println("AutoDriver phoneNo:"+phoneNo);
	System.out.println("+++++++++++++");
	Rapido rapido=new Rapido();
	String name1=rapido.name;
	float charge=rapido.charge;
	String typeOfVehical=rapido.typeOfVehical;
	System.out.println("rapido name:"+name1);
	System.out.println("rapido charge:"+charge);
	System.out.println("rapido vehical:"+typeOfVehical);
	System.out.println("+++++++++++++");
	CabCompany cab=new CabCompany();
	String  companyName=cab.companyName;
	String cabNumber=cab.cabNumber;
	String driverName1=cab.driverName;
	System.out.println("CabCompany name:"+companyName);
	System.out.println("cab number:"+cabNumber);
	System.out.println("cab driverName: "+driverName1);
	System.out.println("+++++++++++++");
	BMTC bus =new BMTC();
	int busNumber=bus.busNumber;
	String driverName2=bus.driverName;
	int charge1=bus.charge;
	System.out.println("BMTC:"+busNumber);
	System.out.println("BMTC:"+driverName2);
	System.out.println("BMTC:"+charge1);
	System.out.println("+++++++++++++");
	FoodDeliveryCompany food=new FoodDeliveryCompany();
	String foodName=food.foodName;
	float price1=food.price;
	int quantity= food.quantity;
	System.out.println("FoodDeliveryCompany:"+foodName);
	System.out.println("FoodDeliveryCompany:"+ price1);
	System.out.println("FoodDeliveryCompany:"+quantity);
	}
}